name: aqueducts
summary: Explore worlds as you go from learning code fundamentals to Javascript
description: |
  All the water has disappeared from your village and it's up to you to save the day! Go on an adventure to connect the water pipes and bring water back to your village. Solve puzzles and hack your way through 15 levels of fun and challenging islands. When you're done, build and program your own levels to challenge other players!
version: '1.2.2'
base: core22
architectures:
- amd64
confinement: strict
grade: stable

apps:
  aqueducts:
    extensions: [gnome]
    command: /Aqueducts/Aqueducts.x86_64
    plugs:
      - audio-playback
      - desktop
      - desktop-legacy
      - joystick
      - network
      - opengl
      - wayland
      - x11

parts:
  aqueducts:
    source: https://github.com/endless-network/Aqueducts_Binary/releases/download/v1.2.2/Aqueducts.zip
    plugin: dump
    override-prime: |
      craftctl default
      chmod +x $CRAFT_PRIME/Aqueducts/Aqueducts.x86_64
  desktop-files:
    plugin: nil
    source: desktop-file
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp * $CRAFT_PART_INSTALL/meta/gui
